### ISSUE TITLE
Being able to compute height for each row

### ISSUE THREAD

**Issue by DanielRamosAcosta** [techniq/mui-virtualized-table#11]
Right now, the `rowHeight` only accepts a Number, but `react-virtualized` accepts both a Number or a Function that returns the Height.

**Comment by techniq** [comment]
@DanielRamosAcosta Seems useful, and should be for the most part just checking if `rowHeight` is a `function` [here](https://github.com/techniq/mui-virtualized-table/blob/master/src/index.js#L381-L385).

I support this with [mui-downshift](https://github.com/techniq/mui-downshift/blob/master/src/Menu.js) although I've been moving away from using react-virtualized, or at least allowing a user to opt-in to windowing when their user case needs it (and not be burdened when not).  It's the reason I created `mui-virtualized-table` from the original `mui-table`.  I am currently in the works to do this similar with `mui-downshfit` (to become `mui-virtualized-downshift` likely).

I'm willing to review and merge a PR if you'd want to tackle this.
