### ISSUE TITLE
How do you make the text in your cell go to the next line?

### ISSUE THREAD

**Issue by rodoabad** [techniq/mui-virtualized-table#13]
If there's a long text, it doesn't go to the next line.

I don't see any ability to override `cellContents`.

https://github.com/techniq/mui-virtualized-table/blob/dd01493ce8ea48731107b61a3ab99c28854e7c9d/src/index.js#L124

**Comment by techniq** [comment]
@rodoabad You should be able to pass in `classes` and override `cellContents`.

**Comment by rodoabad** [comment]
@techniq yeah, I was looking at the props earlier and noticed `classes` was there. Thanks!
