### ISSUE TITLE
withstyles is undefined in 3.0.0

### ISSUE THREAD

**Issue by OHalford-Novetta** [techniq/mui-virtualized-table#45]
After installing v3.0.0-4, I get this error on the browser console "TypeError: Cannot read property 'withstyles' of undefined". The error is in the last line `export default withStyles(styles, { withTheme: true })(MuiTable);`. I think for withStyles, the import has to specifically be at "@material-ui/core/styles".

**Comment by cvanem** [comment]
@OHalford-Novetta Can you try v3.0.0-2 and see if that works?  I'm not seeing the issue on my end.  

I would like to verify the issue and that the proposed change will fix it.  If you could provide a live reproduction of the error that would help.

**Comment by techniq** [comment]
@OHalford-Novetta What version of Material-UI are you using?  Might be before they had the export in the core.

@cvanem We could also switch from the `withStyles` HOC to using the `makeStyles` / `useStyles` hook (I use this predominantly nowadays).

https://material-ui.com/styles/api/#makestyles-styles-options-hook
