### ISSUE TITLE
Unsafe lifecycle method componentWillReceiveProps

### ISSUE THREAD

**Issue by alexanderAnexsys** [techniq/mui-virtualized-table#6]
https://github.com/techniq/mui-virtualized-table/blob/3a74df9bd30e14c1fbcb74db1481fe6236ba5574/src/index.js#L158

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by techniq** [comment]
We can switch to unsafe_componentWillReceiveProps for now.  One reason I created mui-table was to not worry about this for a while (most of my use cases do not need windowing/virtualization)

**Comment by defusioner** [comment]
Hello,

Would not it be better to migrate to some not deprecated lifecycle step, as the renaming won't help in some other next version of React?

Tell me if I can help.

Thanks
